server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/pets-spring"
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/pets-spring"
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none


jwt:
  secret: ${JWT_SECRET:secret-key}


honeycomb:
  beeline:
    enabled: true
    service-name: Spring-JWT-Demo
    dataset: application
    write-key: 0103c8e625a662cfb693a8cf2b4bc084
